# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Booster' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Booster
  pod 'Alamofire', '~> 4.8.2'
  pod 'Kingfisher', '~> 5.0'
  pod 'NMapsMap'
  pod 'SwiftGifOrigin', '~> 1.7.0'

  target 'BoosterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BoosterUITests' do
    # Pods for testing
  end

end
